menu:
    Blog: /
    Archive: /archives/
    # Weibo: http://weibo.com/wxblb
    About: /about/
    GitHub: https://github.com/xiubinwong
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Copyright Infomation
startyear: 2015
